### PR TITLE
Add type="event" to places endpoint

### PR DESCRIPTION
**Pull request by ehunter-usgs**
fixes usgs/hazdev-geoserve-ws#33

This maintains the old geoserve functionality for earthquake-eventpages

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
please rebase

**Comment by ehunter-usgs** [comment]
When reviewing either reinstall or add the feature_code index yourself.

CREATE INDEX geoname_feature_code_index ON geoname (feature_code);

**Comment by jmfee-usgs** [comment]
GeoserveWebService
- in parsePlacesQuery, `query->type` is an array when validating parameter combinations
- in parseRegionsQuery, added `$types` is not needed

PlacesFactory
- add a `getGeonames()` method that is called by `get()` and checks for circle/rectangle
- in `_expandSearch`, `count($results)` needs to be at least `query->limit` instead of exactly
- in `getEventPlaces()`, it may be easier to add places to an array by id and type (add closest place, add capital, then add places with 10k+ people until you have 5), then sort by distance.  This would eliminate need for remove duplicates.
- in `getByCircle()`, should `limit` always auto expand radius, unless `maxradiuskm` is specified?

PlacesFormatter
- is there always a population?  intval turns '' or null to 0.

**Comment by jmfee-usgs** [comment]
I refactored a little in a separate pull request:
https://github.com/usgs/hazdev-geoserve-ws/pull/65

**Pull request closed without merging**
