### PR TITLE
Usgs/hazdev geoserve ws#108

### PR DESCRIPTION
**Pull request by emcwhirter-usgs**
Fixes usgs/hazdev-geoserve-ws#108

### CODE REVIEW

**Comment by emcwhirter-usgs** [comment]
Fixes usgs/hazdev-geoserve-ws#108

**Comment by emartinez-usgs** [comment]
- Make `_NO_DATA_MESSAGE` a configuration option in `_DEFAULTS` as `noDataMessage`.
- Change default `header` value to `null`.

**Comment by jmfee-usgs** [comment]
please rebase

**Comment by emcwhirter-usgs** [comment]
rebased x 1

**Comment by emcwhirter-usgs** [comment]
rebased x 2

**Comment by emartinez-usgs** [comment]
Please incorporate view into LocationApp. It doesn't need to be pretty/perfect yet, but it should be incorporated.

**Comment by emcwhirter-usgs** [comment]
Added Tectonic summary section to LocationApp.

**Comment by emcwhirter-usgs** [comment]
rebased

**Pull request merged**
