### PR TITLE
Added scripts to create and load timezone schema.

### PR DESCRIPTION
**Pull request by hasimpson-usgs**
fixes usgs/hazdev-geoserv-ws#78
fixes usgs/hazdev-geoserv-ws#77

### CODE REVIEW

**Comment by hasimpson-usgs** [comment]
Sorry,  I misspelled geoserve,  so this didn't link to 78/77

**Comment by ehunter-usgs** [comment]
Can we update some of the table/column names to be more consistent?
- Update table name to "timezone" (singular)
- Update geometry column to "shape" (like other tables)

**Comment by ehunter-usgs** [comment]
You updated the path in load_timezone.php for timezones.dat, but didn't actually move the file on the ftp server. The file is still located here:

ftp://hazards.cr.usgs.gov/web/hazdev-geoserve-ws/timezones/timezones.dat

**Comment by ehunter-usgs** [comment]
I don't really care about the file name on the FTP server, but I updated the reference to the local filename load_timezone.php inside setup_database.php

**Pull request merged**
